import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    data: {
      "Muslim.or.id": {
        all: "/api/muslim/",
        type: "/api/muslim/:type",
        listType: [
          "akidah",
          "manhaj",
          "fikih-dan-muamalah",
          "akhlak-dan-nasihat",
          "hadis",
          "landasan-agama",
          "khotbah-jumat",
          "keluarga",
          "tafsir",
          "tazkiyatun-nufus",
          "syiah",
          "ramadan",
          "sejarah-islam",
          "sejarah",
          "fikih",
          "jejak-islam",
          "kesehatan-islami",
          "bahasa-arab",
          "kolom-ti",
        ],
      },
      "Muslimah.or.id": {
        all: "/api/muslimah/",
        type: "/api/muslimah/:type",
        listType: [
		"adab-doa",
		"akhlak-dan-nasihat",
		"akidah",
		"fikih",
		"keluarga-dan-wanita",
		"pendidikan-anak",
		"kesehatan-muslimah",
		"quran",
		"kisah",
		"info-dauroh-kajian",
		"hadis",
		"dari-redaksi",
		"manhaj",
		"nasihat-ulama",
		"ramadan",
		"tazkiyatun-nafs",
        ],
      },
      "Rumaysho": {
        all: "/api/rumaysho/",
        type: "/api/rumaysho/:type",
        listType: [
		"akhlaq",
		"amalan",
		"aqidah",
		"tafsir-al-quran",
		"muamalah",
		"shalat",
		"qolbu",
		"teladan",
		"thoharoh",
		"umum",
		"faedah-ilmu",
		"haji-umrah",
		"jalan-kebenaran",
		"keluarga",
		"khutbah-hari-raya",
		"khutbah-jumat",
		"muslimah",
		"puasa",
		"sosial",
		"ilmu-ushul",
		"zakat",
        ],
      },
	  "Almanhaj": {
        all: "/api/almanhaj",
      },
	  "Pengusaha Muslim": {
        all: "/api/pengusaha-muslim/",
        type: "/api/pengusaha-muslim/:type",
        listType: [
		"artikel",
		"tanya-jawab-syariah",
		"tashfiyah",
		"kontemporer",
		"entrepreneurship",
		"umu",
		"hukum-perdagangan",
		"muamalah",
		"pemasaran",
		"motivasi-diri",
		"rezeki",
		"sumber-daya-manusia",
		"fikih-ibadah",
		"teknologi-informasi",
		"pembukuan-dan-administrasi",
		"nasehat",
		"fikih-pengusaha-muslim",
		"pelayanan-pelanggan",
		"bisnis-rumahan",
		"sharing",
		"research-and-development",
		"ecommerce",
		"seminar-dan-ceramah-kpmi",
		"kisah-sukses",
		"personal-branding",
		"produksi",
		"perdagangan",
		"strategi-bisnis",
		"kewirausahaan",
		"advetorial",
		"zakat",
		"kuliner",
		"perternakan",
		"peluang-usaha",
        ],
      },
	  "Khotbah Jumat": {
        all: "/api/khotbah-jumat/",
        type: "/api/khotbah-jumat/:type",
        listType: [
		"akhlak-dan-muamalah",
		"artikel-khutbah-jumat-2",
		"bersih-hati",
		"pondasi-agama",
		"nasehat",
		"jalan-kebenaran",
		"khutbah-jumat-pilihan",
		"kumpulan-khutbah-jumat-puasa",
		"rumah-tangga",
		"ceramah-singkat",
		"fikih",
		"khotbah-idul-adha",
		"khotbah-idul-fitri",
		"panduan-khutbah-jumat",
		"video-khutbah-jumat",
        ],
      },
      "Konsultasi Syariah": {
        all: "/api/konsultasi-syariah/",
        type: "/api/konsultasi-syariah/:type",
        listType: [
		"fikih",
"aqidah",
"ibadah-fikih",
"sholat",
"halal-haram",
"pernikahan",
"kontemporer",
"pertanyaan-pembaca",
"rumah-tangga",
"dzikir-dan-doa",
"akhlak",
"puasa",
"ramadhan-fikih",
"adab",
"ramadhan",
"wanita",
"muamalah",
"nasehat",
"bersuci",
"hukum-perdagangan",
"fikih-qurban",
"al-quran",
"pergaulan",
"zakat",
"bidah",
"haji",
"darah-wanita",
"berita",
"manajemen-qolbu",
"manhaj",
"anak",
"hadits",
"hutang-piutang",
"jenazah",
"sejarah-islam",
"firqoh-manhaj",
"waris",
"makanan",
"kitab",
"karir",
"download",
"jilbab-wanita",
"pakaian",
"adzan-fikih",
"dari-redaksi-pertanyaan-pembaca",
"muharram",
"aqiqah",
"ebook-download",
"jihad",
        ],
      },
	    "Remaja Islam": {
        all: "/api/khotbah-jumat/",
        type: "/api/khotbah-jumat/:type",
        listType: [
		"fiqih-remaja",
"amalan",
"nasehat",
"pra-nikah",
"menata-hati",
"akhlaq-mulia",
"kisah-teladan",
"jalanku",
"aqidah",
"hidayah-kamu",
"kajian-al-quran",
"kajian-remaja",
"mutiara-islam",
"pojok-muslimah",
"tips",
"cinta",
"dunia-islam",
        ],
      },
    },
  });
}
