export type ListNews = {
  news: string;
  types?: string[];
  zones?: string[];
  isNotAll?: boolean;
};

export const listNews: ListNews[] = [
  {
    news: "Muslim",
    types: [
		"akidah",
		"manhaj",
		"fikih-dan-muamalah",
		"akhlak-dan-nasihat",
		"hadis",
		"landasan-agama",
		"khotbah-jumat",
		"keluarga",
		"tafsir",
		"tazkiyatun-nufus",
		"syiah",
		"ramadan",
		"sejarah-islam",
		"sejarah",
		"fikih",
		"jejak-islam",
		"kesehatan-islami",
		"bahasa-arab",
		"kolom-ti",
        ],
      },
  {
    news: "Muslimah",
    types: [
        	"adab-doa",
		"akhlak-dan-nasihat",
		"akidah",
		"fikih",
		"keluarga-dan-wanita",
		"pendidikan-anak",
		"kesehatan-muslimah",
		"quran",
		"kisah",
		"info-dauroh-kajian",
		"hadis",
		"dari-redaksi",
		"manhaj",
		"nasihat-ulama",
		"ramadan",
		"tazkiyatun-nafs",
        ],
      },
	{
    news: "Rumaysho",
    types: [
        	"akhlaq",
        	"amalan",
		"aqidah",
		"tafsir-al-quran",
		"muamalah",
		"shalat",
		"qolbu",
		"teladan",
		"thoharoh",
		"umum",
		"faedah-ilmu",
		"haji-umrah",
		"jalan-kebenaran",
		"keluarga",
		"khutbah-hari-raya",
		"khutbah-jumat",
		"muslimah",
		"puasa",
		"sosial",
		"ilmu-ushul",
		"zakat",
		"kajian-islam",
		"bisnis",
        ],
    },
	{
	news: "Almanhaj",
	},
	{
    news: "Pengusaha Muslim",
    types: [
		"artikel",
		"tanya-jawab-syariah",
		"tashfiyah",
		"kontemporer",
		"entrepreneurship",
		"umu",
		"hukum-perdagangan",
		"muamalah",
		"pemasaran",
		"motivasi-diri",
		"rezeki",
		"sumber-daya-manusia",
		"fikih-ibadah",
		"teknologi-informasi",
		"pembukuan-dan-administrasi",
		"nasehat",
		"fikih-pengusaha-muslim",
		"pelayanan-pelanggan",
		"bisnis-rumahan",
		"sharing",
		"research-and-development",
		"ecommerce",
		"seminar-dan-ceramah-kpmi",
		"kisah-sukses",
		"personal-branding",
		"produksi",
		"perdagangan",
		"strategi-bisnis",
		"kewirausahaan",
		"advetorial",
		"zakat",
		"kuliner",
		"perternakan",
		"peluang-usaha",
        ],
    },
	{
    news: "Khotbah Jumat",
    types: [
		"akhlak-dan-muamalah",
		"artikel-khutbah-jumat-2",
		"bersih-hati",
		"pondasi-agama",
		"nasehat",
		"jalan-kebenaran",
		"khutbah-jumat-pilihan",
		"kumpulan-khutbah-jumat-puasa",
		"rumah-tangga",
		"ceramah-singkat",
		"fikih",
		"khotbah-idul-adha",
		"khotbah-idul-fitri",
		"panduan-khutbah-jumat",
		"video-khutbah-jumat",
        ],
    },
];
